### ISSUE TITLE
Building does not generate javascript output files

### ISSUE THREAD

**Issue by rhpijnacker** [theintern/intern-a11y#2]
Since I want to write a intern interface, I considered using this project as an example.
However, when I run the "npm run build" command, I get some files copied to _build, but no javascript.

I'm running in Windows 10, node v6.11.

**Comment by jason0x43** [comment]
Odd. Are you seeing any compiler errors? You _should_ end up with something like:

```
_build/
    src/
        A11yReporter.d.ts
        A11yReporter.js
        A11yReporter.js.map
        common.d.ts
        ...
    tests/
        data/
        integration/
        util.js
        util.js.map
        ...
```

**Comment by rhpijnacker** [comment]
No, no output indicating any problems, and no generated files.
By the way... I get the same problem when building intern itself (so maybe the issue should be raised there?)

**Comment by jason0x43** [comment]
I've reproduced the issue on a Windows VM. It looks like our [build scripts](https://github.com/theintern/dev) have some issues on Windows. This will affect all the Intern projects (Intern, Leadfoot, a11y, etc.), but luckily the fix will fix them all.

**Comment by jason0x43** [comment]
I created https://github.com/theintern/dev/issues/8 to track the issue.
